default["control"]["percona"]["encrypted_data_bag"] = "passwords"
default["control"]["database"]["aegir"] = "aegir"
default["control"]["database"]["host"] = "localhost"
default["control"]["database"]["username"] = "root"
default["control"]["database"]["dbname"] = "aegir"
