name             'scratchpads'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures scratchpads'
long_description 'Installs/Configures scratchpads'
version          '0.1.0'

depends 'apt',			'~> 2.7'
depends 'apache2',		'~> 3.0'
depends 'nfs',			'~> 2.1'
depends 'percona',		'~> 0.16'
depends 'php',			'~> 1.5'
depends 'scratchpads',		'~> 0.1'
depends 'database', 		'~> 4.0'
depends 'mysql2_chef_gem',	'~> 1.0'
depends 'sudo',			'~> 2.7'
depends 'git',			'~> 4.2'
depends 'postfix',		'~> 3.6'
depends 'imagemagick',		'~> 0.2'
depends 'gkrellmd',		'~> 0.3'
depends 'varnish',		'~> 2.2'
