name             'scratchpads'
maintainer       'Simon Rycroft'
maintainer_email 's.rycroft@nhm.ac.uk'
license          'CC BY 4.0'
description      'Installs and configures all services required to run a Scratchpads instance'
long_description 'Installs/Configures scratchpads'
version          '0.1.0'

depends 'apache2',         '~> 3.0'
depends 'apt',             '~> 2.7'
depends 'database',        '~> 4.0'
depends 'git',             '~> 4.2'
depends 'gkrellmd',        '~> 0.3'
depends 'hostsfile',       '~> 2.4'
depends 'imagemagick',     '~> 0.2'
depends 'java',            '~> 1.31'
depends 'memcached',       '~> 1.7'
depends 'mmonit',          '~> 0.1'
depends 'monit-ng',        '~> 1.6'
depends 'mysql2_chef_gem', '~> 1.0'
depends 'nfs',             '~> 2.1'
depends 'percona',         '~> 0.16'
depends 'php',             '~> 1.5'
depends 'postfix',         '~> 3.6'
depends 'scratchpads',     '~> 0.1'
depends 'sudo',            '~> 2.7'
depends 'varnish',         '~> 2.2'